In [3]:
import cv2
from cv2 import imread, imwrite
from math import sqrt, pi as CONSTANT_PI, e as CONSTANT_E
import numpy as np

from cv2 import imshow, waitKey, destroyAllWindows

ker_size = 7
sigma = 0.5

def sobel_operator():
    sobel_x = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
    print("Sobel X-axis",sobel_x)
    #sobel_x = np.asarray(sobel_x)
    sobel_y = np.array([[1,2,1],[0,0,0],[-1,-2,-1]])
    print("Sobel Y-axis",sobel_y)
    #sobel_y = np.asarray(sobel_y)
    return (1/8)*sobel_x, (1/8)*sobel_y

def build_Gaussian_Kernel(size, sigma):
    if (size%2==0):
        size+=1
    size_half = (int)(size/2)
    low_bound=-1*size_half
    up_bound=size_half
    kernel = np.zeros((size, size))
    sum=0
    for kernel_x in np.arange( low_bound, up_bound+1 ):
        for kernel_y in np.arange( low_bound, up_bound+1 ):
            kernel[kernel_x+size_half][kernel_y+size_half] = (1/( 2*(CONSTANT_PI)*(sigma**2)*( (CONSTANT_E)**( ( ((kernel_x)**2)+((kernel_y)**2) )/( 2*(sigma**2) ) ) ) ))
            sum = sum + kernel[kernel_x+size_half][kernel_y+size_half]
    for kernel_x in np.arange( low_bound, up_bound+1 ):
        for kernel_y in np.arange( low_bound, up_bound+1 ):
            kernel[kernel_x+size_half][kernel_y+size_half] = (kernel[kernel_x+size_half][kernel_y+size_half]) / sum
    return kernel

def convolve(img, kernel):
    kernel_size = (int)((kernel.shape[0])/2)
    img_abs_mk = img.copy()
    convo_img_mk = np.zeros((img_abs_mk.shape[0], img_abs_mk.shape[1]))
    for img_x in np.arange( kernel_size, ((img.shape[0])-kernel_size) ):
        for img_y in np.arange( kernel_size, ((img.shape[1])-kernel_size) ):
            temp = 0
            for kernel_x in np.arange(-1, 2):
                for kernel_y in np.arange(-1, 2):
                    coordinate_ker = kernel[kernel_x+kernel_size, kernel_y+kernel_size]
                    coordinate_img = img[img_x-kernel_x, img_y-kernel_y]
                    temp = temp + (coordinate_img*coordinate_ker)
            img_abs_mk[img_x][img_y] = abs(temp)
            convo_img_mk[img_x][img_y] = temp
    return convo_img_mk, img_abs_mk

def main():
    image = cv2.imread("task1.png",0)
    edge_x = image.copy()
    edge_y = image.copy()
    gaussianKernel = build_Gaussian_Kernel(ker_size, sigma)
    sobel_x, sobel_y = sobel_operator()
    print(sobel_x)
    print(sobel_y)
    x_edge, x_abs = convolve(image, sobel_x)
    y_edge, y_abs = convolve(image, sobel_y)
    cv2.imwrite("X_edge.png", x_edge)
    cv2.imwrite("Y_edge.png", y_edge)
    cv2.imwrite("X_abs.png", x_abs)
    cv2.imwrite("Y_abs.png", y_abs)  
main()

(600, 900)
Sobel X-axis [[-1  0  1]
 [-2  0  2]
 [-1  0  1]]
Sobel Y-axis [[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]
[[-0.125  0.     0.125]
 [-0.25   0.     0.25 ]
 [-0.125  0.     0.125]]
[[ 0.125  0.25   0.125]
 [ 0.     0.     0.   ]
 [-0.125 -0.25  -0.125]]
